package com.akamyshev.schoolschedule2

import com.akamyshev.schoolschedule2.schedule.ScheduleOfDay
import com.akamyshev.schoolschedule2.schedule.ScheduleOfWeek
import com.akamyshev.schoolschedule2.schedule.School
import com.example.alexandr.schooltime.schedule.Lesson
import io.realm.Realm
import io.realm.RealmList

/**
 * Created by alexandr on 16.08.17.
 */
class RealmGenerateUtils {

    companion object {
        fun init(realm: Realm) {
            val school = School()
            school.schoolName = "g4"
            school.version = 1

            val schedule = School()

            var lessonsInDay: ScheduleOfDay
            var classInSchool: ScheduleOfWeek

            //11 класс
            classInSchool = ScheduleOfWeek("11Р")
            //---------------------------------------------------------------------------------------
            lessonsInDay = ScheduleOfDay(getOrdinalOfDay("Понедельник"))
            lessonsInDay.addLesson("Технология гр 2", "115")
            lessonsInDay.addLesson("Ин.яз П1, П2, Б1, Б2, Б3, Б4", "П1 (215), П2 (311), Б1 (111), Б2 (317), Б3 (115), Б4 (315)")
            lessonsInDay.addLesson("Физика П, Химия П, Естествознание", "Физика П (213)\nХимия П (312)\nЕстествознание (118)")
            lessonsInDay.addLesson("Физика П, Химия П, Естествознание", "Физика П (213)\nХимия П (312)\nЕстествознание (118)")
            lessonsInDay.addLesson("Литература П, Б1, Б2", "П (119), Б1 (116), Б2 (305)")
            lessonsInDay.addLesson("Физ-ра (Т), Русский (Р), ОРР (Е)", "Физ-ра (Т)(с/з)\nРусский (Р)(305)\nОРР (307)")
            lessonsInDay.addLesson("Физ-ра (Т), Русский (Р), ОРР (Е)", "Физ-ра (Т)(с/з)\nРусский (Р)(305)\nОРР (307)")
            lessonsInDay.addLesson("Химия Б", "312")
            classInSchool.addScheduleOfDay(lessonsInDay)
            //---------------------------------------------------------------------------------------
            lessonsInDay = ScheduleOfDay(getOrdinalOfDay("Вторник"))
            lessonsInDay.addLesson("Математика П1, П2, Б1, Б2", "П1 (308), П2 (301), Б1 (302), Б2(304)")
            lessonsInDay.addLesson("Математика П1, П2, Б1, Б2", "П1 (308), П2 (301), Б1 (302), Б2(304)")
            lessonsInDay.addLesson("Биология П, Физика П, Литература П, История П", "Биология П (118), Физика П (213), Литература П (119), История П (214)")
            lessonsInDay.addLesson("Биология П, Физика П, Литература П, История П", "Биология П (118), Физика П (213), Литература П (119), История П (214)")
            lessonsInDay.addLesson("Физика Б, КРР", "Физика Б (213)\nКРР (314)")
            lessonsInDay.addLesson("Физика Б, Информатика П", "Физика Б (213)\nИнформатика П (307)")
            lessonsInDay.addLesson("Ин.яз П1, П2, Химия П, Информатика П, Технология гр 1", "Ин.яз П1 (311), П2 (215), Химия П (312), Информатика П (307), Технология гр 1 (302)")
            classInSchool.addScheduleOfDay(lessonsInDay)
            //---------------------------------------------------------------------------------------
            lessonsInDay = ScheduleOfDay(getOrdinalOfDay("Среда"))
            lessonsInDay.addLesson("Классный час", "В вашем кабинете")
            lessonsInDay.addLesson("Математика П1, П2, ЛОМ", "Математика П1 (308)\nМатематика П2 (301)\nЛОМ (118)")
            lessonsInDay.addLesson("Ин.яз П1, П2, Информатика Б1, Б2, Б3", "Ин.яз П1 (311), П2 (215), Информатика Б1 (310), Б2 (207), Б3 (307)")
            lessonsInDay.addLesson("Естествознание, Физика П", "Естествознание (118)\nФизика П (213)")
            lessonsInDay.addLesson("История П, Б1, Б2", "П (214)\nБ1 (л/з)\n Б2 (313)")
            lessonsInDay.addLesson("История П, Б1, Б2", "П (214)\nБ1 (л/з)\n Б2 (313)")
            lessonsInDay.addLesson("Физ-ра (Р), ОРР (Т), Психология (Е)", "Физ-ра (Р)(с/з)\nОРР (Т)(214)\nПсихология (Е)(309)")
            lessonsInDay.addLesson("Физ-ра (Р), ОРР (Т), Русский (Е)", "Физ-ра (Р)(с/з)\nОРР (Т)(214)\nРусский (Е)(119)")
            classInSchool.addScheduleOfDay(lessonsInDay)
            //---------------------------------------------------------------------------------------
            lessonsInDay = ScheduleOfDay(getOrdinalOfDay("Четверг"))
            lessonsInDay.addLesson("Математика П1, П2, Б1, Б2", "П1 (308), П2 (301), Б1 (307), Б2(312)")
            lessonsInDay.addLesson("Математика П1, П2, Б1, Б2", "П1 (308), П2 (301), Б1 (307), Б2(312)")
            lessonsInDay.addLesson("Русский язык П1, П2, П3, Б", "П1 (119), П2 (303), П3 (116), Б (304)")
            lessonsInDay.addLesson("Русский язык П1, П2, П3", "П1 (119), П2 (303), П3 (116)")
            lessonsInDay.addLesson("Литература П, Б1, Б2", "П (119), Б1 (303), Б2 (116)")
            lessonsInDay.addLesson("Литература П, Б1, Б2", "П (119), Б1 (303), Б2 (116)")
            lessonsInDay.addLesson("МРЗ, Право гр1, гр2", "МРЗ (213), Право гр1 (307), гр2 (214)")
            lessonsInDay.addLesson("Информатика П", "207")
            classInSchool.addScheduleOfDay(lessonsInDay)
            //---------------------------------------------------------------------------------------
            lessonsInDay = ScheduleOfDay(getOrdinalOfDay("Пятница"))
            lessonsInDay.addLesson("Биология П, Б", "П (118), Б (л.з)")
            lessonsInDay.addLesson("Общество П1, П2, Б1, Б2", "П1 (214), П2 (115), Б1 (312), Б2(314)")
            lessonsInDay.addLesson("Общество П1, П2, Б1, Б2", "П1 (214), П2 (115), Б1 (312), Б2(314)")
            lessonsInDay.addLesson("Ин.яз П1, П2, Б1, Б2, Б3, Б4", "П1 (215), П2 (311), Б1 (214), Б2 (111), Б3 (315), Б4 (317)")
            lessonsInDay.addLesson("Ин.яз П1, П2, Б1, Б2, Б3, Б4", "П1 (215), П2 (311), Б1 (310), Б2 (111), Б3 (315), Б4 (317)")
            lessonsInDay.addLesson("Физ-ра (E), ОРР (Р), Психология (Т)", "Физ-ра (E)(c/з)\nОРР (Р)(304)\nПсихология (Т)(303)")
            lessonsInDay.addLesson("Физ-ра (E), ОРР (Р), Русский (Т)", "Физ-ра (E)(c/з)\nОРР (Р)(304)\nРусский (Т)(116)")
            classInSchool.addScheduleOfDay(lessonsInDay)
            //---------------------------------------------------------------------------------------
            lessonsInDay = ScheduleOfDay(getOrdinalOfDay("Суббота"))
            lessonsInDay.addLesson("Информатика П, Общество П1, П2", "Информатика П (307)\nОбщество П1 (214), П2 (115)")
            lessonsInDay.addLesson("Генетика и пол гр1, гр2", "гр1 (118), гр2 (314)")
            lessonsInDay.addLesson("Математика П1, П2, ЛОМ", "Математика П1 (308)\nМатематика П2 (301)\nЛОМ (313)")
            lessonsInDay.addLesson("География, Автодело гр 2", "География (212)\nАвтодело гр 2 (313)")
            lessonsInDay.addLesson("Ин.яз П1, П2, Автодело гр 1", "Ин.яз П1 (215), П2 (311), Автодело гр 1 (313)")
            classInSchool.addScheduleOfDay(lessonsInDay)
            //---------------------------------------------------------------------------------------
            schedule.addScheduleOfWeek(classInSchool)
            //-----------------------------------------------------
            //10 класс
            classInSchool = ScheduleOfWeek("10Р")
            //---------------------------------------------------------------------------------------
            lessonsInDay = ScheduleOfDay(getOrdinalOfDay("Понедельник"))
            lessonsInDay.addLesson("Физика П, Химия П, История П, Информатика ВШЭ", "Физика П(213), Химия П(312), История П(л/з), Информатика ВШЭ(207)")
            lessonsInDay.addLesson("Физика П, Химия П, История П, Информатика ВШЭ", "Физика П(213), Химия П(312), История П(л/з), Информатика ВШЭ(207)")
            lessonsInDay.addLesson("Русский язык ВШЭ, П1, П2, Б", "ВШЭ (303), П1 (306), П2 (304), Б (315)")
            lessonsInDay.addLesson("Русский П1, П2, Теория познания ВШЭ", "Русский П1 (306), П2 (304)\nТеория познания ВШЭ (акт. зал)")
            lessonsInDay.addLesson("Математика П, География, Теория познания ВШЭ", "Математика П (313)\nГеография (212)\nТеория познания ВШЭ (акт. зал)")
            lessonsInDay.addLesson("Математика ВШЭ, П", "ВШЭ (308), П (313)")
            lessonsInDay.addLesson("Химия Б, Естествознание", "Химия Б (312)\nЕстествознание (118)")
            lessonsInDay.addLesson("Ин.яз ВШЭ, П, Черчение", "Ин.яз ВШЭ (215), П (315)\nЧерчение (302)")
            classInSchool.addScheduleOfDay(lessonsInDay)
            //---------------------------------------------------------------------------------------
            lessonsInDay = ScheduleOfDay(getOrdinalOfDay("Вторник"))
            lessonsInDay.addLesson("Физика П, Химия П, Литература ВШЭ, Информатика ВШЭ", "Физика П(213), Химия П(312), Литература ВШЭ (116), П (317), Информатика ВШЭ(207)")
            lessonsInDay.addLesson("Физика П, Биология ВШЭ, П, Литература ВШЭ, Информатика ВШЭ", "Физика П(213), Биология ВШЭ (315), П(118), Литература ВШЭ (116), П (317), Информатика ВШЭ(207)")
            lessonsInDay.addLesson("Математика ВШЭ, П, Б", "ВШЭ (308), П (313), Б (304)")
            lessonsInDay.addLesson("Математика ВШЭ, П, Б", "ВШЭ (308), П (313), Б (304)")
            lessonsInDay.addLesson("ОРР З, КРР Н, Биология ВШЭ", "ОРР З (л/з)\nКРР Н (303)\nБиология ВШЭ (315)")
            lessonsInDay.addLesson("Физ-ра Н, ОРР З", "Физ-ра Н (c/з)\nОРР З (л/з)")
            lessonsInDay.addLesson("Физ-ра Н, Психология З", "Физ-ра Н (c/з)\nПсихология З (308)")
            classInSchool.addScheduleOfDay(lessonsInDay)
            //---------------------------------------------------------------------------------------
            lessonsInDay = ScheduleOfDay(getOrdinalOfDay("Среда"))
            lessonsInDay.addLesson("Классный час", "В вашем кабинете")
            lessonsInDay.addLesson("Физика П, Биология ВШЭ, П, Ин.яз ВШЭ, П", "Физика П (213), Биология ВШЭ (112), П (317), Ин.яз ВШЭ (215), П (315)")
            lessonsInDay.addLesson("Литература ВШЭ, П, Б1, Б2", "ВШЭ (119), П (112), Б1 (303), Б2 (304)")
            lessonsInDay.addLesson("Литература ВШЭ, П, Б1, Б2", "ВШЭ (119), П (112), Б1 (303), Б2 (304)")
            lessonsInDay.addLesson("Физика Б, Естествознание", "Физика Б (213)\nЕстествознание (118)")
            lessonsInDay.addLesson("Физика Б, Естествознание", "Физика Б (213)\nЕстествознание (118)")
            lessonsInDay.addLesson("Общество П, Математика ВШЭ", "Общество П (л/з)\nМатематика ВШЭ (308)")
            lessonsInDay.addLesson("Автодело гр 1, Генетика и пол, ЛОМ", "Автодело гр 1 (307)\nГенетика и пол (118)\nЛОМ (302)")
            lessonsInDay.addLesson("Автодело гр 2, Правоведение", "Автодело гр 2 (307), Правоведение (л/з)")
            classInSchool.addScheduleOfDay(lessonsInDay)
            //---------------------------------------------------------------------------------------
            lessonsInDay = ScheduleOfDay(getOrdinalOfDay("Четверг"))
            lessonsInDay.addLesson("Ин.яз ВШЭ, П, Б1, Б2", "ВШЭ (215), П (315), Б1 (117), Б2 (311)")
            lessonsInDay.addLesson("Ин.яз ВШЭ, П, Б1, Б2", "ВШЭ (215), П (315), Б1 (117), Б2 (311)")
            lessonsInDay.addLesson("16:00", "")
            classInSchool.addScheduleOfDay(lessonsInDay)
            //---------------------------------------------------------------------------------------
            lessonsInDay = ScheduleOfDay(getOrdinalOfDay("Пятница"))
            lessonsInDay.addLesson("Литература ВШЭ, П, Б1, Б2", "ВШЭ (119), П (116), Б1 (303), Б2 (304)")
            lessonsInDay.addLesson("Математика ВШЭ, П, Б", "ВШЭ (308), П (313), Б (305)")
            lessonsInDay.addLesson("Математика ВШЭ, П, Б", "ВШЭ (308), П (313), Б (305)")
            lessonsInDay.addLesson("Психология Н, КРР З", "Психология Н (314)\nКРР З (304)")
            lessonsInDay.addLesson("Биология П, Б, Информатика Б гр 3", "Биология П (118), Б (л/з)\nИнформатика Б гр 3 (207)")
            lessonsInDay.addLesson("Ин.яз ВШЭ, П, Б1, Б2", "ВШЭ (215), П (315), Б1 (117), Б2 (311)")
            lessonsInDay.addLesson("Ин.яз ВШЭ, П, Информатика Б1, Б2", "Ин.яз ВШЭ (215), П (315)\nИнформатика Б1 (310), Б2 (207)")
            classInSchool.addScheduleOfDay(lessonsInDay)
            //---------------------------------------------------------------------------------------
            lessonsInDay = ScheduleOfDay(getOrdinalOfDay("Суббота"))
            lessonsInDay.addLesson("История П, Б1, 2", "История П (315), Б1, 2 (л/з)")
            lessonsInDay.addLesson("История П, Б1, 2", "История П (315), Б1, 2 (л/з)")
            lessonsInDay.addLesson("Общество П, Б", "П (л/з), Б (214)")
            lessonsInDay.addLesson("Общество П, Б", "П (л/з), Б (214)")
            lessonsInDay.addLesson("Русский ВШЭ, П1, П2", "ВШЭ (303), П1 (306), П2 (304)")
            lessonsInDay.addLesson("Физ-ра З, ОРР Н, Русский ВШЭ", "Физ-ра З (с/з)\nОРР Н (л/з)\nРусский ВШЭ (303)")
            lessonsInDay.addLesson("Физ-ра З, ОРР Н", "Физ-ра З (с/з)\nОРР Н (л/з)")
            classInSchool.addScheduleOfDay(lessonsInDay)

            schedule.addScheduleOfWeek(classInSchool)
            //-----------------------------------------------------
            //9Р класс
            classInSchool = ScheduleOfWeek("9Р")
            //---------------------------------------------------------------------------------------
            lessonsInDay = ScheduleOfDay(getOrdinalOfDay("Понедельник"))
            lessonsInDay.addLesson("Психология", "307")
            lessonsInDay.addLesson("География", "212")
            lessonsInDay.addLesson("Ин. язык", "317/111")
            lessonsInDay.addLesson("История", "л/з")
            lessonsInDay.addLesson("Право", "л/з")
            classInSchool.addScheduleOfDay(lessonsInDay)
            //---------------------------------------------------------------------------------------
            lessonsInDay = ScheduleOfDay(getOrdinalOfDay("Вторник"))
            lessonsInDay.addLesson("Физ-ра", "с/з")
            lessonsInDay.addLesson("Физ-ра", "с/з")
            lessonsInDay.addLesson("Задачи с ПиМ", "301")
            lessonsInDay.addLesson("Общество", "л/з")
            lessonsInDay.addLesson("Математика", "301")
            lessonsInDay.addLesson("ОКР", "306")
            classInSchool.addScheduleOfDay(lessonsInDay)
            //---------------------------------------------------------------------------------------
            lessonsInDay = ScheduleOfDay(getOrdinalOfDay("Среда"))
            lessonsInDay.addLesson("Классный час", "213")
            lessonsInDay.addLesson("Химия", "312")
            lessonsInDay.addLesson("Литература", "306")
            lessonsInDay.addLesson("Физика в задачах", "212")
            lessonsInDay.addLesson("Литература", "306")
            lessonsInDay.addLesson("Информатика", "207/310")
            lessonsInDay.addLesson("Искусство", "115")
            classInSchool.addScheduleOfDay(lessonsInDay)
            //---------------------------------------------------------------------------------------
            lessonsInDay = ScheduleOfDay(getOrdinalOfDay("Четверг"))
            lessonsInDay.addLesson("Русский язык", "306")
            lessonsInDay.addLesson("География", "212")
            lessonsInDay.addLesson("Математика", "301")
            lessonsInDay.addLesson("История", "314")
            lessonsInDay.addLesson("Ин. язык", "317/111")
            lessonsInDay.addLesson("Литература", "306")
            classInSchool.addScheduleOfDay(lessonsInDay)
            //---------------------------------------------------------------------------------------
            lessonsInDay = ScheduleOfDay(getOrdinalOfDay("Пятница"))
            lessonsInDay.addLesson("Физика", "213")
            lessonsInDay.addLesson("Русский язык", "306")
            lessonsInDay.addLesson("Биология", "л/з")
            lessonsInDay.addLesson("Математика", "301")
            lessonsInDay.addLesson("Литература", "306")
            lessonsInDay.addLesson("Математика", "301")
            classInSchool.addScheduleOfDay(lessonsInDay)
            //---------------------------------------------------------------------------------------
            lessonsInDay = ScheduleOfDay(getOrdinalOfDay("Суббота"))
            lessonsInDay.addLesson("Математика", "301")
            lessonsInDay.addLesson("Ин. язык", "317/111")
            lessonsInDay.addLesson("Физика", "213")
            lessonsInDay.addLesson("Химия", "312")
            lessonsInDay.addLesson("Информатика", "207/310")
            lessonsInDay.addLesson("Биология", "118")
            classInSchool.addScheduleOfDay(lessonsInDay)

            schedule.addScheduleOfWeek(classInSchool)
            //-----------------------------------------------------
            //9Ч класс
            classInSchool = ScheduleOfWeek("9Ч")
            //---------------------------------------------------------------------------------------
            lessonsInDay = ScheduleOfDay(getOrdinalOfDay("Понедельник"))
            lessonsInDay.addLesson("География", "212")
            lessonsInDay.addLesson("Биология", "118")
            lessonsInDay.addLesson("Литература", "116")
            lessonsInDay.addLesson("Русский язык", "116")
            lessonsInDay.addLesson("Психология", "115")
            classInSchool.addScheduleOfDay(lessonsInDay)
            //---------------------------------------------------------------------------------------
            lessonsInDay = ScheduleOfDay(getOrdinalOfDay("Вторник"))
            lessonsInDay.addLesson("Биология", "118")
            lessonsInDay.addLesson("Искусство", "115")
            lessonsInDay.addLesson("История", "314")
            lessonsInDay.addLesson("Физика", "116")
            lessonsInDay.addLesson("Литература", "116")
            lessonsInDay.addLesson("Математика", "304")
            classInSchool.addScheduleOfDay(lessonsInDay)
            //---------------------------------------------------------------------------------------
            lessonsInDay = ScheduleOfDay(getOrdinalOfDay("Среда"))
            lessonsInDay.addLesson("Классный час", "314")
            lessonsInDay.addLesson("История", "314")
            lessonsInDay.addLesson("Ин. язык", "111/317")
            lessonsInDay.addLesson("Математика", "314")
            lessonsInDay.addLesson("Химия", "312")
            lessonsInDay.addLesson("Общество", "314")
            lessonsInDay.addLesson("Физика в задачах", "212")
            classInSchool.addScheduleOfDay(lessonsInDay)
            //---------------------------------------------------------------------------------------
            lessonsInDay = ScheduleOfDay(getOrdinalOfDay("Четверг"))
            lessonsInDay.addLesson("Ин. язык", "317/111")
            lessonsInDay.addLesson("Литература", "116")
            lessonsInDay.addLesson("Математика", "312")
            lessonsInDay.addLesson("Физ-ра", "с/з")
            lessonsInDay.addLesson("Физ-ра", "с/з")
            lessonsInDay.addLesson("Информатика", "207/310")
            classInSchool.addScheduleOfDay(lessonsInDay)
            //---------------------------------------------------------------------------------------
            lessonsInDay = ScheduleOfDay(getOrdinalOfDay("Пятница"))
            lessonsInDay.addLesson("Правоведение", "314")
            lessonsInDay.addLesson("Литература", "116")
            lessonsInDay.addLesson("Русский язык", "116")
            lessonsInDay.addLesson("Математика", "305")
            lessonsInDay.addLesson("Задачи с параметрами", "305")
            lessonsInDay.addLesson("География", "212")
            classInSchool.addScheduleOfDay(lessonsInDay)
            //---------------------------------------------------------------------------------------
            lessonsInDay = ScheduleOfDay(getOrdinalOfDay("Суббота"))
            lessonsInDay.addLesson("Математика", "313")
            lessonsInDay.addLesson("ОКР", "116")
            lessonsInDay.addLesson("Ин. язык", "317/111")
            lessonsInDay.addLesson("Физика", "213")
            lessonsInDay.addLesson("Химия", "312")
            lessonsInDay.addLesson("Информатика", "207,310")
            classInSchool.addScheduleOfDay(lessonsInDay)
            schedule.addScheduleOfWeek(classInSchool)
            //-----------------------------------------------------
            //9Б класс
            classInSchool = ScheduleOfWeek("9Б")
            //---------------------------------------------------------------------------------------
            lessonsInDay = ScheduleOfDay(getOrdinalOfDay("Понедельник"))
            lessonsInDay.addLesson("-", "") //Нет урока
            lessonsInDay.addLesson("Пс", "307")
            lessonsInDay.addLesson("Ис", "л/з")
            lessonsInDay.addLesson("Ин", "317/111")
            lessonsInDay.addLesson("Б", "118")
            lessonsInDay.addLesson("Р", "306")
            classInSchool.addScheduleOfDay(lessonsInDay)
            //---------------------------------------------------------------------------------------
            lessonsInDay = ScheduleOfDay(getOrdinalOfDay("Вторник"))
            lessonsInDay.addLesson("Л", "306")
            lessonsInDay.addLesson("О", "л/з")
            lessonsInDay.addLesson("Л", "306")
            lessonsInDay.addLesson("ОКР", "306")
            lessonsInDay.addLesson("Г", "212")
            lessonsInDay.addLesson("Х", "312")
            classInSchool.addScheduleOfDay(lessonsInDay)
            //---------------------------------------------------------------------------------------
            lessonsInDay = ScheduleOfDay(getOrdinalOfDay("Среда"))
            lessonsInDay.addLesson("КЧ", "118")
            lessonsInDay.addLesson("Пр", "л/з")
            lessonsInDay.addLesson("М", "301")
            lessonsInDay.addLesson("Иф", "207/310")
            lessonsInDay.addLesson("Задачи с параметрами", "301")
            lessonsInDay.addLesson("Б", "118")
            classInSchool.addScheduleOfDay(lessonsInDay)
            //---------------------------------------------------------------------------------------
            lessonsInDay = ScheduleOfDay(getOrdinalOfDay("Четверг"))
            lessonsInDay.addLesson("Фи", "213")
            lessonsInDay.addLesson("Ин", "317/111")
            lessonsInDay.addLesson("Р", "306")
            lessonsInDay.addLesson("Л", "306")
            lessonsInDay.addLesson("Ис", "л/з")
            lessonsInDay.addLesson("М", "301")
            classInSchool.addScheduleOfDay(lessonsInDay)
            //---------------------------------------------------------------------------------------
            lessonsInDay = ScheduleOfDay(getOrdinalOfDay("Пятница"))
            lessonsInDay.addLesson("Иф", "207/310")
            lessonsInDay.addLesson("М", "301")
            lessonsInDay.addLesson("И", "115")
            lessonsInDay.addLesson("Г", "212")
            lessonsInDay.addLesson("М", "301")
            lessonsInDay.addLesson("Фи", "213")
            classInSchool.addScheduleOfDay(lessonsInDay)
            //---------------------------------------------------------------------------------------
            lessonsInDay = ScheduleOfDay(getOrdinalOfDay("Суббота"))
            lessonsInDay.addLesson("Ин", "317/111")
            lessonsInDay.addLesson("Л", "306")
            lessonsInDay.addLesson("Х", "312")
            lessonsInDay.addLesson("Фа", "с/з")
            lessonsInDay.addLesson("Фа", "с/з")
            lessonsInDay.addLesson("М", "301")
            classInSchool.addScheduleOfDay(lessonsInDay)
            schedule.addScheduleOfWeek(classInSchool)
            //-----------------------------------------------------
            //8Р класс
            classInSchool = ScheduleOfWeek("8Р")
            //---------------------------------------------------------------------------------------
            lessonsInDay = ScheduleOfDay(getOrdinalOfDay("Понедельник"))
            lessonsInDay.addLesson("Ин", "311/317")
            lessonsInDay.addLesson("Р", "309")
            lessonsInDay.addLesson("Ис", "314")
            lessonsInDay.addLesson("О", "314")
            lessonsInDay.addLesson("М", "302")
            lessonsInDay.addLesson("Х", "312")
            classInSchool.addScheduleOfDay(lessonsInDay)
            //---------------------------------------------------------------------------------------
            lessonsInDay = ScheduleOfDay(getOrdinalOfDay("Вторник"))
            lessonsInDay.addLesson("Р", "309")
            lessonsInDay.addLesson("Л", "309")
            lessonsInDay.addLesson("М", "302")
            lessonsInDay.addLesson("Г", "212")
            lessonsInDay.addLesson("Фа", "с")
            lessonsInDay.addLesson("Фа", "с")
            classInSchool.addScheduleOfDay(lessonsInDay)
            //---------------------------------------------------------------------------------------
            lessonsInDay = ScheduleOfDay(getOrdinalOfDay("Среда"))
            lessonsInDay.addLesson("КЧ", "309")
            lessonsInDay.addLesson("-", "")
            lessonsInDay.addLesson("Пра", "314")
            lessonsInDay.addLesson("ИЗО", "115")
            lessonsInDay.addLesson("М", "302")
            lessonsInDay.addLesson("ПиЭКК", "309")
            lessonsInDay.addLesson("Х", "312")
            classInSchool.addScheduleOfDay(lessonsInDay)
            //---------------------------------------------------------------------------------------
            lessonsInDay = ScheduleOfDay(getOrdinalOfDay("Четверг"))
            lessonsInDay.addLesson("Иф", "310/207")
            lessonsInDay.addLesson("ЗсПиМ", "302")
            lessonsInDay.addLesson("Ин", "311/317")
            lessonsInDay.addLesson("Б", "118")
            lessonsInDay.addLesson("М", "302")
            lessonsInDay.addLesson("Фи", "213")
            classInSchool.addScheduleOfDay(lessonsInDay)
            //---------------------------------------------------------------------------------------
            lessonsInDay = ScheduleOfDay(getOrdinalOfDay("Пятница"))
            lessonsInDay.addLesson("-", "")
            lessonsInDay.addLesson("Фи", "213")
            lessonsInDay.addLesson("Ин", "311/317")
            lessonsInDay.addLesson("М", "302")
            lessonsInDay.addLesson("Словесность", "309")
            lessonsInDay.addLesson("Л", "309")
            classInSchool.addScheduleOfDay(lessonsInDay)
            //---------------------------------------------------------------------------------------
            lessonsInDay = ScheduleOfDay(getOrdinalOfDay("Суббота"))
            lessonsInDay.addLesson("Технология", "310/207")
            lessonsInDay.addLesson("Г", "212")
            lessonsInDay.addLesson("Р", "309")
            lessonsInDay.addLesson("Л", "309")
            lessonsInDay.addLesson("Б", "118")
            lessonsInDay.addLesson("Ис", "314")
            classInSchool.addScheduleOfDay(lessonsInDay)
            schedule.addScheduleOfWeek(classInSchool)
            //-----------------------------------------------------
            //8Ш класс
            classInSchool = ScheduleOfWeek("8Ш")
            //---------------------------------------------------------------------------------------
            lessonsInDay = ScheduleOfDay(getOrdinalOfDay("Понедельник"))
            lessonsInDay.addLesson("Ис", "314")
            lessonsInDay.addLesson("Иф", "310/207")
            lessonsInDay.addLesson("Г", "212")
            lessonsInDay.addLesson("Р", "305")
            lessonsInDay.addLesson("Ин", "317/315")
            lessonsInDay.addLesson("О", "314")
            classInSchool.addScheduleOfDay(lessonsInDay)
            //---------------------------------------------------------------------------------------
            lessonsInDay = ScheduleOfDay(getOrdinalOfDay("Вторник"))
            lessonsInDay.addLesson("Л", "305")
            lessonsInDay.addLesson("Фи", "307")
            lessonsInDay.addLesson("Р", "305")
            lessonsInDay.addLesson("Х", "312")
            lessonsInDay.addLesson("М", "304")
            classInSchool.addScheduleOfDay(lessonsInDay)
            //---------------------------------------------------------------------------------------
            lessonsInDay = ScheduleOfDay(getOrdinalOfDay("Среда"))
            lessonsInDay.addLesson("КЧ", "207")
            lessonsInDay.addLesson("-", "")
            lessonsInDay.addLesson("М", "308")
            lessonsInDay.addLesson("Ин", "311/315")
            lessonsInDay.addLesson("Р", "305")
            lessonsInDay.addLesson("Л", "305")
            lessonsInDay.addLesson("О", "314")
            classInSchool.addScheduleOfDay(lessonsInDay)
            //---------------------------------------------------------------------------------------
            lessonsInDay = ScheduleOfDay(getOrdinalOfDay("Четверг"))
            lessonsInDay.addLesson("Б", "118")
            lessonsInDay.addLesson("Фа", "с")
            lessonsInDay.addLesson("Фа", "с")
            lessonsInDay.addLesson("М", "312")
            lessonsInDay.addLesson("Р", "305")
            lessonsInDay.addLesson("ЗсПиМ", "312")
            classInSchool.addScheduleOfDay(lessonsInDay)
            //---------------------------------------------------------------------------------------
            lessonsInDay = ScheduleOfDay(getOrdinalOfDay("Пятница"))
            lessonsInDay.addLesson("М", "305")
            lessonsInDay.addLesson("Ин", "311/315")
            lessonsInDay.addLesson("Г", "212")
            lessonsInDay.addLesson("И", "115")
            lessonsInDay.addLesson("Фи", "213")
            lessonsInDay.addLesson("ПиЭКК", "л")
            classInSchool.addScheduleOfDay(lessonsInDay)
            //---------------------------------------------------------------------------------------
            lessonsInDay = ScheduleOfDay(getOrdinalOfDay("Суббота"))
            lessonsInDay.addLesson("Б", "118")
            lessonsInDay.addLesson("М", "313")
            lessonsInDay.addLesson("Р", "305")
            lessonsInDay.addLesson("Т", "310/207")
            lessonsInDay.addLesson("Пра", "314")
            lessonsInDay.addLesson("Х", "312")
            classInSchool.addScheduleOfDay(lessonsInDay)
            schedule.addScheduleOfWeek(classInSchool)
            //-----------------------------------------------------
            //8Б класс
            classInSchool = ScheduleOfWeek("8Б")
            //---------------------------------------------------------------------------------------
            lessonsInDay = ScheduleOfDay(getOrdinalOfDay("Понедельник"))
            lessonsInDay.addLesson("Р", "119")
            lessonsInDay.addLesson("М", "302")
            lessonsInDay.addLesson("ИЗО", "115")
            lessonsInDay.addLesson("Л", "119")
            lessonsInDay.addLesson("Х", "312")
            lessonsInDay.addLesson("С", "119")
            classInSchool.addScheduleOfDay(lessonsInDay)
            //---------------------------------------------------------------------------------------
            lessonsInDay = ScheduleOfDay(getOrdinalOfDay("Вторник"))
            lessonsInDay.addLesson("ПиЭКК", "л")
            lessonsInDay.addLesson("Ис", "314")
            lessonsInDay.addLesson("Г", "212")
            lessonsInDay.addLesson("М", "302")
            lessonsInDay.addLesson("Х", "312")
            lessonsInDay.addLesson("Пра", "314")
            classInSchool.addScheduleOfDay(lessonsInDay)
            //---------------------------------------------------------------------------------------
            lessonsInDay = ScheduleOfDay(getOrdinalOfDay("Среда"))
            lessonsInDay.addLesson("КЧ", "114")
            lessonsInDay.addLesson("Иф", "301/207")
            lessonsInDay.addLesson("М", "302")
            lessonsInDay.addLesson("Б", "116")
            lessonsInDay.addLesson("Р", "119")
            lessonsInDay.addLesson("Ин", "311/317")
            lessonsInDay.addLesson("Л", "119")
            classInSchool.addScheduleOfDay(lessonsInDay)
            //---------------------------------------------------------------------------------------
            lessonsInDay = ScheduleOfDay(getOrdinalOfDay("Четверг"))
            lessonsInDay.addLesson("ЗсПиМ", "302")
            lessonsInDay.addLesson("Б", "118")
            lessonsInDay.addLesson("О", "314")
            lessonsInDay.addLesson("Т", "310/207")
            lessonsInDay.addLesson("Ф", "213")
            lessonsInDay.addLesson("Ин", "311/317")
            classInSchool.addScheduleOfDay(lessonsInDay)
            //---------------------------------------------------------------------------------------
            lessonsInDay = ScheduleOfDay(getOrdinalOfDay("Пятница"))
            lessonsInDay.addLesson("Г", "212")
            lessonsInDay.addLesson("М", "302")
            lessonsInDay.addLesson("Р", "119")
            lessonsInDay.addLesson("Фи", "213")
            lessonsInDay.addLesson("Л", "119")
            classInSchool.addScheduleOfDay(lessonsInDay)
            //---------------------------------------------------------------------------------------
            lessonsInDay = ScheduleOfDay(getOrdinalOfDay("Суббота"))
            lessonsInDay.addLesson("-", "")
            lessonsInDay.addLesson("М", "302")
            lessonsInDay.addLesson("Ис", "314")
            lessonsInDay.addLesson("Ин", "311/317")
            lessonsInDay.addLesson("Фа", "с")
            lessonsInDay.addLesson("Фа", "с")
            classInSchool.addScheduleOfDay(lessonsInDay)
            schedule.addScheduleOfWeek(classInSchool)
            //-----------------------------------------------------
            //8В класс
            classInSchool = ScheduleOfWeek("8В")
            //---------------------------------------------------------------------------------------
            lessonsInDay = ScheduleOfDay(getOrdinalOfDay("Понедельник"))
            lessonsInDay.addLesson("Иф", "310/207")
            lessonsInDay.addLesson("Р", "305")
            lessonsInDay.addLesson("М", "313")
            lessonsInDay.addLesson("Ин", "311/315")
            lessonsInDay.addLesson("Ис", "314")
            lessonsInDay.addLesson("Г", "212")
            classInSchool.addScheduleOfDay(lessonsInDay)
            //---------------------------------------------------------------------------------------
            lessonsInDay = ScheduleOfDay(getOrdinalOfDay("Вторник"))
            lessonsInDay.addLesson("О", "314")
            lessonsInDay.addLesson("Л", "305")
            lessonsInDay.addLesson("ИЗО", "115")
            lessonsInDay.addLesson("Пра", "314")
            lessonsInDay.addLesson("Р", "305")
            lessonsInDay.addLesson("М", "313")
            classInSchool.addScheduleOfDay(lessonsInDay)
            //---------------------------------------------------------------------------------------
            lessonsInDay = ScheduleOfDay(getOrdinalOfDay("Среда"))
            lessonsInDay.addLesson("КЧ", "313")
            lessonsInDay.addLesson("Р", "305")
            lessonsInDay.addLesson("Б", "116")
            lessonsInDay.addLesson("М", "313")
            lessonsInDay.addLesson("Ин", "311/315")
            lessonsInDay.addLesson("Х", "312")
            lessonsInDay.addLesson("Л", "305")
            classInSchool.addScheduleOfDay(lessonsInDay)
            //---------------------------------------------------------------------------------------
            lessonsInDay = ScheduleOfDay(getOrdinalOfDay("Четверг"))
            lessonsInDay.addLesson("М", "313")
            lessonsInDay.addLesson("Фи", "213")
            lessonsInDay.addLesson("ЗсПиМ", "313")
            lessonsInDay.addLesson("Р", "305")
            lessonsInDay.addLesson("Фа", "с")
            lessonsInDay.addLesson("Фа", "с")
            classInSchool.addScheduleOfDay(lessonsInDay)
            //---------------------------------------------------------------------------------------
            lessonsInDay = ScheduleOfDay(getOrdinalOfDay("Пятница"))
            lessonsInDay.addLesson("Ин", "311/315")
            lessonsInDay.addLesson("Б", "л")
            lessonsInDay.addLesson("Ф", "213")
            lessonsInDay.addLesson("ПиЭКК", "л")
            lessonsInDay.addLesson("М", "313")
            classInSchool.addScheduleOfDay(lessonsInDay)
            //---------------------------------------------------------------------------------------
            lessonsInDay = ScheduleOfDay(getOrdinalOfDay("Суббота"))
            lessonsInDay.addLesson("Х", "312")
            lessonsInDay.addLesson("Р", "305")
            lessonsInDay.addLesson("Т", "310/207")
            lessonsInDay.addLesson("Ис", "314")
            lessonsInDay.addLesson("Г", "212")
            classInSchool.addScheduleOfDay(lessonsInDay)
            schedule.addScheduleOfWeek(classInSchool)
            //-----------------------------------------------------
            //7А класс
            classInSchool = ScheduleOfWeek("7А")
            //---------------------------------------------------------------------------------------
            lessonsInDay = ScheduleOfDay(getOrdinalOfDay("Понедельник"))
            lessonsInDay.addLesson("Б", "118")
            lessonsInDay.addLesson("Р", "304")
            lessonsInDay.addLesson("Иф", "207/310")
            lessonsInDay.addLesson("О", "302")
            lessonsInDay.addLesson("Фи", "213")
            lessonsInDay.addLesson("Ин", "117/315")
            classInSchool.addScheduleOfDay(lessonsInDay)
            //---------------------------------------------------------------------------------------
            lessonsInDay = ScheduleOfDay(getOrdinalOfDay("Вторник"))
            lessonsInDay.addLesson("Т1", "307")
            lessonsInDay.addLesson("Г", "212")
            lessonsInDay.addLesson("Б", "309")
            lessonsInDay.addLesson("Пр", "307")
            lessonsInDay.addLesson("Му", "114")
            lessonsInDay.addLesson("ИЗО", "115")
            classInSchool.addScheduleOfDay(lessonsInDay)
            //---------------------------------------------------------------------------------------
            lessonsInDay = ScheduleOfDay(getOrdinalOfDay("Среда"))
            lessonsInDay.addLesson("КЧ", "309")
            lessonsInDay.addLesson("Р", "304")
            lessonsInDay.addLesson("Ге", "301")
            lessonsInDay.addLesson("Ис", "309")
            lessonsInDay.addLesson("А", "301")
            lessonsInDay.addLesson("Ин", "117/315")
            lessonsInDay.addLesson("Фи", "213")
            classInSchool.addScheduleOfDay(lessonsInDay)
            //---------------------------------------------------------------------------------------
            lessonsInDay = ScheduleOfDay(getOrdinalOfDay("Четверг"))
            lessonsInDay.addLesson("Р", "")
            lessonsInDay.addLesson("Ис", "")
            lessonsInDay.addLesson("Г", "")
            lessonsInDay.addLesson("Л", "")
            lessonsInDay.addLesson("А", "")
            lessonsInDay.addLesson("Большая перемена, Кляксы, КЛИО, Совенок", "Большая перемена (114), Кляксы (115), КЛИО (307), Совенок (л/з)")
            classInSchool.addScheduleOfDay(lessonsInDay)
            //---------------------------------------------------------------------------------------
            lessonsInDay = ScheduleOfDay(getOrdinalOfDay("Пятница"))
            lessonsInDay.addLesson("А", "301")
            lessonsInDay.addLesson("Р", "304")
            lessonsInDay.addLesson("Ин", "117/315")
            lessonsInDay.addLesson("Т2", "307")
            lessonsInDay.addLesson("С", "304")
            classInSchool.addScheduleOfDay(lessonsInDay)
            //---------------------------------------------------------------------------------------
            lessonsInDay = ScheduleOfDay(getOrdinalOfDay("Суббота"))
            lessonsInDay.addLesson("Р", "304")
            lessonsInDay.addLesson("Л", "304")
            lessonsInDay.addLesson("Фа", "с")
            lessonsInDay.addLesson("Фа", "с")
            lessonsInDay.addLesson("Ге", "301")
            classInSchool.addScheduleOfDay(lessonsInDay)
            schedule.addScheduleOfWeek(classInSchool)
            //-----------------------------------------------------
            //7Б класс
            classInSchool = ScheduleOfWeek("7Б")
            //---------------------------------------------------------------------------------------
            lessonsInDay = ScheduleOfDay(getOrdinalOfDay("Понедельник"))
            lessonsInDay.addLesson("Ин", "117/112")
            lessonsInDay.addLesson("А", "308")
            lessonsInDay.addLesson("Л", "309")
            lessonsInDay.addLesson("Г", "212")
            lessonsInDay.addLesson("Р", "309")
            lessonsInDay.addLesson("Фи", "213")
            classInSchool.addScheduleOfDay(lessonsInDay)
            //---------------------------------------------------------------------------------------
            lessonsInDay = ScheduleOfDay(getOrdinalOfDay("Вторник"))
            lessonsInDay.addLesson("Фа", "с")
            lessonsInDay.addLesson("Фа", "с")
            lessonsInDay.addLesson("А", "307")
            lessonsInDay.addLesson("Р", "309")
            lessonsInDay.addLesson("Л", "309")
            lessonsInDay.addLesson("Б", "118")
            classInSchool.addScheduleOfDay(lessonsInDay)
            //---------------------------------------------------------------------------------------
            lessonsInDay = ScheduleOfDay(getOrdinalOfDay("Среда"))
            lessonsInDay.addLesson("КЧ", "207")
            lessonsInDay.addLesson("Пр", "309")
            lessonsInDay.addLesson("Фи", "213")
            lessonsInDay.addLesson("Иф", "207/310")
            lessonsInDay.addLesson("ИЗО", "115")
            lessonsInDay.addLesson("А", "307")
            lessonsInDay.addLesson("Ин", "112/117")
            classInSchool.addScheduleOfDay(lessonsInDay)
            //---------------------------------------------------------------------------------------
            lessonsInDay = ScheduleOfDay(getOrdinalOfDay("Четверг"))
            lessonsInDay.addLesson("Му", "114")
            lessonsInDay.addLesson("Р", "309")
            lessonsInDay.addLesson("Ге", "305")
            lessonsInDay.addLesson("Ис", "л")
            lessonsInDay.addLesson("С", "309")
            lessonsInDay.addLesson("Большая перемена, Кляксы, КЛИО, Совенок", "Большая перемена (114), Кляксы (115), КЛИО (307), Совенок (л/з)")
            classInSchool.addScheduleOfDay(lessonsInDay)
            //---------------------------------------------------------------------------------------
            lessonsInDay = ScheduleOfDay(getOrdinalOfDay("Пятница"))
            lessonsInDay.addLesson("Р", "309")
            lessonsInDay.addLesson("Л", "309")
            lessonsInDay.addLesson("Ге", "307")
            lessonsInDay.addLesson("Б", "118")
            lessonsInDay.addLesson("О", "302")
            lessonsInDay.addLesson("Т1", "307")
            classInSchool.addScheduleOfDay(lessonsInDay)
            //---------------------------------------------------------------------------------------
            lessonsInDay = ScheduleOfDay(getOrdinalOfDay("Суббота"))
            lessonsInDay.addLesson("Г", "212")
            lessonsInDay.addLesson("Ис", "115")
            lessonsInDay.addLesson("Ин", "117/112")
            lessonsInDay.addLesson("Т2", "307")
            classInSchool.addScheduleOfDay(lessonsInDay)
            schedule.addScheduleOfWeek(classInSchool)
            //-----------------------------------------------------
            //7М класс
            classInSchool = ScheduleOfWeek("7М")
            //---------------------------------------------------------------------------------------
            lessonsInDay = ScheduleOfDay(getOrdinalOfDay("Понедельник"))
            lessonsInDay.addLesson("А", "313")
            lessonsInDay.addLesson("Ин", "117/112")
            lessonsInDay.addLesson("Ис", "301")
            lessonsInDay.addLesson("Т", "307")
            lessonsInDay.addLesson("О", "307")
            lessonsInDay.addLesson("Р", "303")
            classInSchool.addScheduleOfDay(lessonsInDay)
            //---------------------------------------------------------------------------------------
            lessonsInDay = ScheduleOfDay(getOrdinalOfDay("Вторник"))
            lessonsInDay.addLesson("-", "")
            lessonsInDay.addLesson("А", "313")
            lessonsInDay.addLesson("Р", "303")
            lessonsInDay.addLesson("Л", "303")
            lessonsInDay.addLesson("ИЗО", "115")
            lessonsInDay.addLesson("Пр", "302")
            classInSchool.addScheduleOfDay(lessonsInDay)
            //---------------------------------------------------------------------------------------
            lessonsInDay = ScheduleOfDay(getOrdinalOfDay("Среда"))
            lessonsInDay.addLesson("КЧ", "114")
            lessonsInDay.addLesson("Му", "114")
            lessonsInDay.addLesson("Фа", "с")
            lessonsInDay.addLesson("Фа", "с")
            lessonsInDay.addLesson("Р", "303")
            lessonsInDay.addLesson("Л", "303")
            lessonsInDay.addLesson("Ге", "313")
            classInSchool.addScheduleOfDay(lessonsInDay)
            //---------------------------------------------------------------------------------------
            lessonsInDay = ScheduleOfDay(getOrdinalOfDay("Четверг"))
            lessonsInDay.addLesson("-", "207/310")
            lessonsInDay.addLesson("Иф", "213")
            lessonsInDay.addLesson("Фи", "313")
            lessonsInDay.addLesson("А", "212")
            lessonsInDay.addLesson("Г", "212")
            lessonsInDay.addLesson("Большая перемена, Кляксы, КЛИО, Совенок", "Большая перемена (114), Кляксы (115), КЛИО (307), Совенок (л/з)")
            classInSchool.addScheduleOfDay(lessonsInDay)
            //---------------------------------------------------------------------------------------
            lessonsInDay = ScheduleOfDay(getOrdinalOfDay("Пятница"))
            lessonsInDay.addLesson("Ге", "313")
            lessonsInDay.addLesson("Г", "212")
            lessonsInDay.addLesson("Р", "303")
            lessonsInDay.addLesson("С", "303")
            lessonsInDay.addLesson("Ин", "112/117")
            lessonsInDay.addLesson("Б", "118")
            classInSchool.addScheduleOfDay(lessonsInDay)
            //---------------------------------------------------------------------------------------
            lessonsInDay = ScheduleOfDay(getOrdinalOfDay("Суббота"))
            lessonsInDay.addLesson("Ин", "112/117")
            lessonsInDay.addLesson("Фи", "213")
            lessonsInDay.addLesson("Ис", "115")
            lessonsInDay.addLesson("Р", "303")
            lessonsInDay.addLesson("Б", "119")
            classInSchool.addScheduleOfDay(lessonsInDay)
            schedule.addScheduleOfWeek(classInSchool)
            //-----------------------------------------------------
            //7И класс
            classInSchool = ScheduleOfWeek("7И")
            //---------------------------------------------------------------------------------------
            lessonsInDay = ScheduleOfDay(getOrdinalOfDay("Понедельник"))
            lessonsInDay.addLesson("Фа", "с")
            lessonsInDay.addLesson("Фа", "с")
            lessonsInDay.addLesson("А", "308")
            lessonsInDay.addLesson("Ис", "301")
            lessonsInDay.addLesson("Р", "304")
            lessonsInDay.addLesson("Б", "118")
            classInSchool.addScheduleOfDay(lessonsInDay)
            //---------------------------------------------------------------------------------------
            lessonsInDay = ScheduleOfDay(getOrdinalOfDay("Вторник"))
            lessonsInDay.addLesson("Г", "")
            lessonsInDay.addLesson("Пр", "")
            lessonsInDay.addLesson("Му", "")
            lessonsInDay.addLesson("ИЗО", "")
            lessonsInDay.addLesson("Ге", "")
            classInSchool.addScheduleOfDay(lessonsInDay)
            //---------------------------------------------------------------------------------------
            lessonsInDay = ScheduleOfDay(getOrdinalOfDay("Среда"))
            lessonsInDay.addLesson("КЧ", "313")
            lessonsInDay.addLesson("О", "307")
            lessonsInDay.addLesson("Б", "118")
            lessonsInDay.addLesson("А", "308")
            lessonsInDay.addLesson("Ин", "112/117")
            lessonsInDay.addLesson("Р", "304")
            lessonsInDay.addLesson("Л", "304")
            classInSchool.addScheduleOfDay(lessonsInDay)
            //---------------------------------------------------------------------------------------
            lessonsInDay = ScheduleOfDay(getOrdinalOfDay("Четверг"))
            lessonsInDay.addLesson("Г", "212")
            lessonsInDay.addLesson("Р", "304")
            lessonsInDay.addLesson("Ис", "л")
            lessonsInDay.addLesson("Фи", "213")
            lessonsInDay.addLesson("С", "304")
            classInSchool.addScheduleOfDay(lessonsInDay)
            //---------------------------------------------------------------------------------------
            lessonsInDay = ScheduleOfDay(getOrdinalOfDay("Пятница"))
            lessonsInDay.addLesson("Ге", "308")
            lessonsInDay.addLesson("Иф", "207/310")
            lessonsInDay.addLesson("Р", "304")
            lessonsInDay.addLesson("Ин", "112/117")
            lessonsInDay.addLesson("С", "307")
            classInSchool.addScheduleOfDay(lessonsInDay)
            //---------------------------------------------------------------------------------------
            lessonsInDay = ScheduleOfDay(getOrdinalOfDay("Суббота"))
            lessonsInDay.addLesson("Фи", "213")
            lessonsInDay.addLesson("Ин", "112/117")
            lessonsInDay.addLesson("Р", "304")
            lessonsInDay.addLesson("Л", "304")
            lessonsInDay.addLesson("А", "308")
            classInSchool.addScheduleOfDay(lessonsInDay)
            schedule.addScheduleOfWeek(classInSchool)
            //-----------------------------------------------------
            //6Щ класс
            classInSchool = ScheduleOfWeek("6Щ")
            //---------------------------------------------------------------------------------------
            lessonsInDay = ScheduleOfDay(getOrdinalOfDay("Понедельник"))
            lessonsInDay.addLesson("Л", "116")
            lessonsInDay.addLesson("Р", "116")
            lessonsInDay.addLesson("Му", "114")
            lessonsInDay.addLesson("Ин", "112/215")
            lessonsInDay.addLesson("О", "301")
            classInSchool.addScheduleOfDay(lessonsInDay)
            //---------------------------------------------------------------------------------------
            lessonsInDay = ScheduleOfDay(getOrdinalOfDay("Вторник"))
            lessonsInDay.addLesson("ИЗО", "214")
            lessonsInDay.addLesson("Пр", "214")
            lessonsInDay.addLesson("Т", "207/310")
            lessonsInDay.addLesson("М", "301")
            lessonsInDay.addLesson("Ин", "112,215")
            lessonsInDay.addLesson("Р", "116")
            classInSchool.addScheduleOfDay(lessonsInDay)
            //---------------------------------------------------------------------------------------
            lessonsInDay = ScheduleOfDay(getOrdinalOfDay("Среда"))
            lessonsInDay.addLesson("КЧ", "")
            lessonsInDay.addLesson("Р", "116")
            lessonsInDay.addLesson("ЗОЖ", "312")
            lessonsInDay.addLesson("Ис", "307")
            lessonsInDay.addLesson("С", "116")
            lessonsInDay.addLesson("Л", "116")
            lessonsInDay.addLesson("К тайнам слова, Математика вокруг нас, КЛИО, Наслаждайся английским", "К тайнам слова (116), Математика вокруг нас (301), КЛИО (307), Наслаждайся английским (311)")
            classInSchool.addScheduleOfDay(lessonsInDay)
            //---------------------------------------------------------------------------------------
            lessonsInDay = ScheduleOfDay(getOrdinalOfDay("Четверг"))
            lessonsInDay.addLesson("Фа", "с")
            lessonsInDay.addLesson("Фа", "с")
            lessonsInDay.addLesson("Т", "207/310")
            lessonsInDay.addLesson("М", "301")
            lessonsInDay.addLesson("И", "307")
            classInSchool.addScheduleOfDay(lessonsInDay)
            //---------------------------------------------------------------------------------------
            lessonsInDay = ScheduleOfDay(getOrdinalOfDay("Пятница"))
            lessonsInDay.addLesson("Ин", "112/215")
            lessonsInDay.addLesson("Б", "118")
            lessonsInDay.addLesson("М", "301")
            lessonsInDay.addLesson("Г", "312")
            lessonsInDay.addLesson("Р", "116")
            lessonsInDay.addLesson("Л", "116")
            classInSchool.addScheduleOfDay(lessonsInDay)
            //---------------------------------------------------------------------------------------
            lessonsInDay = ScheduleOfDay(getOrdinalOfDay("Суббота"))
            lessonsInDay.addLesson("Р", "116")
            lessonsInDay.addLesson("М", "301")
            lessonsInDay.addLesson("Р", "116")
            lessonsInDay.addLesson("М", "301")
            classInSchool.addScheduleOfDay(lessonsInDay)
            schedule.addScheduleOfWeek(classInSchool)
            //-----------------------------------------------------
            //6О класс
            classInSchool = ScheduleOfWeek("6О")
            //---------------------------------------------------------------------------------------
            lessonsInDay = ScheduleOfDay(getOrdinalOfDay("Понедельник"))
            lessonsInDay.addLesson("М", "302")
            lessonsInDay.addLesson("Р", "306")
            lessonsInDay.addLesson("Ин", "112/215")
            lessonsInDay.addLesson("Т", "207/310")
            lessonsInDay.addLesson("Р", "306")
            classInSchool.addScheduleOfDay(lessonsInDay)
            //---------------------------------------------------------------------------------------
            lessonsInDay = ScheduleOfDay(getOrdinalOfDay("Вторник"))
            lessonsInDay.addLesson("О", "119")
            lessonsInDay.addLesson("ЗОЖ", "312")
            lessonsInDay.addLesson("Фа", "с")
            lessonsInDay.addLesson("Фа", "с")
            lessonsInDay.addLesson("Р", "306")
            lessonsInDay.addLesson("Ин", "112/215")
            classInSchool.addScheduleOfDay(lessonsInDay)
            //---------------------------------------------------------------------------------------
            lessonsInDay = ScheduleOfDay(getOrdinalOfDay("Среда"))
            lessonsInDay.addLesson("КЧ", "")
            lessonsInDay.addLesson("Р", "306")
            lessonsInDay.addLesson("Пр", "214")
            lessonsInDay.addLesson("М", "302")
            lessonsInDay.addLesson("Ис", "307")
            lessonsInDay.addLesson("Л", "306")
            lessonsInDay.addLesson("К тайнам слова, Математика вокруг нас, КЛИО, Наслаждайся английским", "К тайнам слова (116), Математика вокруг нас (301), КЛИО (307), Наслаждайся английским (311)")
            classInSchool.addScheduleOfDay(lessonsInDay)
            //---------------------------------------------------------------------------------------
            lessonsInDay = ScheduleOfDay(getOrdinalOfDay("Четверг"))
            lessonsInDay.addLesson("-", "")
            lessonsInDay.addLesson("ИЗО", "115")
            lessonsInDay.addLesson("Б", "118")
            lessonsInDay.addLesson("Ис", "307")
            lessonsInDay.addLesson("Р", "306")
            lessonsInDay.addLesson("Ин", "112/215")
            classInSchool.addScheduleOfDay(lessonsInDay)
            //---------------------------------------------------------------------------------------
            lessonsInDay = ScheduleOfDay(getOrdinalOfDay("Пятница"))
            lessonsInDay.addLesson("Л", "306")
            lessonsInDay.addLesson("Му", "114")
            lessonsInDay.addLesson("Б", "118")
            lessonsInDay.addLesson("Р", "306")
            lessonsInDay.addLesson("Г", "212")
            lessonsInDay.addLesson("М", "302")
            classInSchool.addScheduleOfDay(lessonsInDay)
            //---------------------------------------------------------------------------------------
            lessonsInDay = ScheduleOfDay(getOrdinalOfDay("Суббота"))
            lessonsInDay.addLesson("С", "306")
            lessonsInDay.addLesson("Т", "207/310")
            lessonsInDay.addLesson("Л", "306")
            lessonsInDay.addLesson("М", "302")
            classInSchool.addScheduleOfDay(lessonsInDay)
            schedule.addScheduleOfWeek(classInSchool)
            //-----------------------------------------------------
            //6К класс
            classInSchool = ScheduleOfWeek("6К")
            //---------------------------------------------------------------------------------------
            lessonsInDay = ScheduleOfDay(getOrdinalOfDay("Понедельник"))
            lessonsInDay.addLesson("-", "")
            lessonsInDay.addLesson("Р", "119")
            lessonsInDay.addLesson("Л", "119")
            lessonsInDay.addLesson("ИЗО", "115")
            lessonsInDay.addLesson("М", "308")
            lessonsInDay.addLesson("Ин", "112/215")
            classInSchool.addScheduleOfDay(lessonsInDay)
            //---------------------------------------------------------------------------------------
            lessonsInDay = ScheduleOfDay(getOrdinalOfDay("Вторник"))
            lessonsInDay.addLesson("Пр", "214")
            lessonsInDay.addLesson("Му", "114")
            lessonsInDay.addLesson("ЗОЖ", "312")
            lessonsInDay.addLesson("Т", "207/310")
            lessonsInDay.addLesson("Р", "119")
            lessonsInDay.addLesson("С", "119")
            classInSchool.addScheduleOfDay(lessonsInDay)
            //---------------------------------------------------------------------------------------
            lessonsInDay = ScheduleOfDay(getOrdinalOfDay("Среда"))
            lessonsInDay.addLesson("КЧ", "")
            lessonsInDay.addLesson("Р", "119")
            lessonsInDay.addLesson("О", "309")
            lessonsInDay.addLesson("Ин", "111/215")
            lessonsInDay.addLesson("М", "308")
            lessonsInDay.addLesson("Р", "119")
            lessonsInDay.addLesson("К тайнам слова, Математика вокруг нас, КЛИО, Наслаждайся английским", "К тайнам слова (116), Математика вокруг нас (301), КЛИО (307), Наслаждайся английским (311)")
            classInSchool.addScheduleOfDay(lessonsInDay)
            //---------------------------------------------------------------------------------------
            lessonsInDay = ScheduleOfDay(getOrdinalOfDay("Четверг"))
            lessonsInDay.addLesson("Р", "119")
            lessonsInDay.addLesson("Л", "119")
            lessonsInDay.addLesson("Фа", "с")
            lessonsInDay.addLesson("Фа", "с")
            lessonsInDay.addLesson("Ин", "112,315")
            classInSchool.addScheduleOfDay(lessonsInDay)
            //---------------------------------------------------------------------------------------
            lessonsInDay = ScheduleOfDay(getOrdinalOfDay("Пятница"))
            lessonsInDay.addLesson("Ис", "312")
            lessonsInDay.addLesson("Р", "119")
            lessonsInDay.addLesson("Т", "207/310")
            lessonsInDay.addLesson("Л", "119")
            lessonsInDay.addLesson("М", "308")
            lessonsInDay.addLesson("Г", "312")
            classInSchool.addScheduleOfDay(lessonsInDay)
            //---------------------------------------------------------------------------------------
            lessonsInDay = ScheduleOfDay(getOrdinalOfDay("Суббота"))
            lessonsInDay.addLesson("Б", "314")
            lessonsInDay.addLesson("М", "308")
            lessonsInDay.addLesson("Ис", "307")
            lessonsInDay.addLesson("М", "308")
            classInSchool.addScheduleOfDay(lessonsInDay)
            schedule.addScheduleOfWeek(classInSchool)
            //-----------------------------------------------------
            //6П класс
            classInSchool = ScheduleOfWeek("6П")
            //---------------------------------------------------------------------------------------
            lessonsInDay = ScheduleOfDay(getOrdinalOfDay("Понедельник"))
            lessonsInDay.addLesson("Р", "306")
            lessonsInDay.addLesson("О", "301")
            lessonsInDay.addLesson("Ин", "311")
            lessonsInDay.addLesson("Пра", "Библиотека")
            lessonsInDay.addLesson("М", "311")
            lessonsInDay.addLesson("Л", "116")
            classInSchool.addScheduleOfDay(lessonsInDay)
            //---------------------------------------------------------------------------------------
            lessonsInDay = ScheduleOfDay(getOrdinalOfDay("Вторник"))
            lessonsInDay.addLesson("-", "")
            lessonsInDay.addLesson("Р", "311")
            lessonsInDay.addLesson("Л", "311")
            lessonsInDay.addLesson("Б", "311")
            lessonsInDay.addLesson("Т", "311")
            lessonsInDay.addLesson("М", "308")
            classInSchool.addScheduleOfDay(lessonsInDay)
            //---------------------------------------------------------------------------------------
            lessonsInDay = ScheduleOfDay(getOrdinalOfDay("Среда"))
            lessonsInDay.addLesson("КЧ", "")
            lessonsInDay.addLesson("Ин", "311")
            lessonsInDay.addLesson("М", "311")
            lessonsInDay.addLesson("Р", "306")
            lessonsInDay.addLesson("Фа", "с")
            lessonsInDay.addLesson("ИЗО", "115")
            lessonsInDay.addLesson("К тайнам слова, Математика вокруг нас, КЛИО, Наслаждайся английским", "К тайнам слова (116), Математика вокруг нас (301), КЛИО (307), Наслаждайся английским (311)")
            classInSchool.addScheduleOfDay(lessonsInDay)
            //---------------------------------------------------------------------------------------
            lessonsInDay = ScheduleOfDay(getOrdinalOfDay("Четверг"))
            lessonsInDay.addLesson("Л", "116")
            lessonsInDay.addLesson("Р", "306")
            lessonsInDay.addLesson("Ис", "307")
            lessonsInDay.addLesson("М", "308")
            lessonsInDay.addLesson("Фа", "с")
            classInSchool.addScheduleOfDay(lessonsInDay)
            //---------------------------------------------------------------------------------------
            lessonsInDay = ScheduleOfDay(getOrdinalOfDay("Пятница"))
            lessonsInDay.addLesson("Му", "114")
            lessonsInDay.addLesson("Т", "307")
            lessonsInDay.addLesson("Р", "306")
            lessonsInDay.addLesson("М", "116")
            lessonsInDay.addLesson("ЗОЖ", "312")
            lessonsInDay.addLesson("Р", "306")
            classInSchool.addScheduleOfDay(lessonsInDay)
            //---------------------------------------------------------------------------------------
            lessonsInDay = ScheduleOfDay(getOrdinalOfDay("Суббота"))
            lessonsInDay.addLesson("Ис", "311")
            lessonsInDay.addLesson("Ин", "311")
            lessonsInDay.addLesson("Г", "212")
            lessonsInDay.addLesson("С", "306")
            classInSchool.addScheduleOfDay(lessonsInDay)
            schedule.addScheduleOfWeek(classInSchool)
            //-----------------------------------------------------

            realm.executeTransaction { realm -> realm.insert(schedule) }

            //System.out.println(new Gson().toJson(schedule));
        }

        fun clear() {
            Realm.getDefaultInstance().executeTransaction { it.deleteAll() }
        }

        internal fun getOrdinalOfDay(day: String): Int {
            val daysNames = arrayOf("Понедельник", "Вторник", "Среда", "Четверг", "Пятница", "Суббота")
            for (i in daysNames.indices)
                if (daysNames[i] == day) return i
            return -1
        }
    }
}